font pango:FiraCode Nerd Font 10
seat seat0 xcursor_theme Adwaita 20

default_border none
default_floating_border none
hide_edge_borders smart

for_window [class=".*"] titlebar_none
for_window [class=".*"] border pixel 0
for_window [class=".*"] opacity 0.92

gaps inner 12
gaps outer 24
smart_gaps off

# --- Window blur ---
blur enable
blur_xray disable
blur_passes 3
blur_radius 6
blur_noise 0.00
blur_brightness 1
blur_contrast 1
blur_saturation 1


# --- Rounded corners ---
#corner_radius 0

# --- Shadows ---
shadows disable
shadow_blur_radius 8
shadow_color #00000022
shadow_offset 0 0

# class                 border    bg        text    indicator child_border
client.focused          #00000000 #00000000 #ffffff #00000000 #00000000
client.focused_inactive #00000000 #00000000 #888888 #00000000 #00000000
client.unfocused        #00000000 #00000000 #555555 #00000000 #00000000
client.urgent           #00000000 #00000000 #ffffff #00000000 #00000000

set $gnome-schema org.gnome.desktop.interface

exec_always {
    gsettings set $gnome-schema gtk-theme 'adw-gtk3-dark'
    gsettings set $gnome-schema cursor-theme 'Adwaita'
    gsettings set $gnome-schema font-name 'FiraCode Nerd Font'
    gsettings set $gnome-schema color-scheme 'prefer-dark'
}
