# ~/.config/sway/conf.d/autostart.conf

exec ~/.config/sway/scripts/run_noctalia.sh

exec dbus-update-activation-environment --systemd --all
exec /usr/bin/gnome-keyring-daemon --start --components=secrets,pkcs11,ssh

exec_always autotiling

exec otd-daemon 
