# ~/.config/sway/conf.d/input.conf


input type:keyboard {
    xkb_layout "latam,us"
    xkb_variant ",altgr-intl"
    xkb_options "grp:alt_shift_toggle" 
    repeat_delay 300
    repeat_rate 50
}

input type:touchpad {
    tap enabled
    natural_scroll enabled
    scroll_method two_finger
    click_method clickfinger
    pointer_accel 0.3
    dwt enabled
    middle_emulation enabled
}
input "7247:72:SIGMACHIP_Usb_Mouse" {
    pointer_accel -0.66
    accel_profile "flat"
}
